export const SET_ACCOUNT = "SET_ACCOUNT";

export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAIL = "CREATE_ACCOUNT_FAIL";

export const GET_LIST_ACCOUNT = "GET_LIST_ACCOUNT";
export const GET_LIST_ACCOUNT_SUCCESS = "GET_LIST_ACCOUNT_SUCCESS";
export const GET_LIST_ACCOUNT_FAIL = "GET_LIST_ACCOUNT_FAIL";
