export const CREATE_BILL = "CREATE_BILL";
export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const CREATE_BILL_FAIL = "CREATE_BILL_FAIL";

export const GET_LIST_BILL = "GET_LIST_BILL";
export const GET_LIST_BILL_SUCCESS = "GET_LIST_BILL_SUCCESS";
export const GET_LIST_BILL_FAIL = "GET_LIST_BILL_FAIL";

export const GET_BILL_BY_USERNAME = "GET_BILL_BY_USERNAME";
export const GET_BILL_BY_USERNAME_SUCCESS = "GET_BILL_BY_USERNAME_SUCCESS";
export const GET_BILL_BY_USERNAME_FAIL = "GET_BILL_BY_USERNAME_FAIL";
