export const GET_PRODUCTS_DETAIL = "GET_PRODUCTS_DETAIL";
export const GET_PRODUCTS_DETAIL_SUCCESS = "GET_PRODUCTS_DETAIL_SUCCESS";
export const GET_PRODUCTS_DETAIL_FAIL = "GET_PRODUCTS_DETAIL_FAIL";
